
//input ports
add mapped point clk clk -type PI PI
add mapped point A[15] A[15] -type PI PI
add mapped point A[14] A[14] -type PI PI
add mapped point A[13] A[13] -type PI PI
add mapped point A[12] A[12] -type PI PI
add mapped point A[11] A[11] -type PI PI
add mapped point A[10] A[10] -type PI PI
add mapped point A[9] A[9] -type PI PI
add mapped point A[8] A[8] -type PI PI
add mapped point A[7] A[7] -type PI PI
add mapped point A[6] A[6] -type PI PI
add mapped point A[5] A[5] -type PI PI
add mapped point A[4] A[4] -type PI PI
add mapped point A[3] A[3] -type PI PI
add mapped point A[2] A[2] -type PI PI
add mapped point A[1] A[1] -type PI PI
add mapped point A[0] A[0] -type PI PI
add mapped point B[23] B[23] -type PI PI
add mapped point B[22] B[22] -type PI PI
add mapped point B[21] B[21] -type PI PI
add mapped point B[20] B[20] -type PI PI
add mapped point B[19] B[19] -type PI PI
add mapped point B[18] B[18] -type PI PI
add mapped point B[17] B[17] -type PI PI
add mapped point B[16] B[16] -type PI PI
add mapped point B[15] B[15] -type PI PI
add mapped point B[14] B[14] -type PI PI
add mapped point B[13] B[13] -type PI PI
add mapped point B[12] B[12] -type PI PI
add mapped point B[11] B[11] -type PI PI
add mapped point B[10] B[10] -type PI PI
add mapped point B[9] B[9] -type PI PI
add mapped point B[8] B[8] -type PI PI
add mapped point B[7] B[7] -type PI PI
add mapped point B[6] B[6] -type PI PI
add mapped point B[5] B[5] -type PI PI
add mapped point B[4] B[4] -type PI PI
add mapped point B[3] B[3] -type PI PI
add mapped point B[2] B[2] -type PI PI
add mapped point B[1] B[1] -type PI PI
add mapped point B[0] B[0] -type PI PI

//output ports
add mapped point RES[39] RES[39] -type PO PO
add mapped point RES[38] RES[38] -type PO PO
add mapped point RES[37] RES[37] -type PO PO
add mapped point RES[36] RES[36] -type PO PO
add mapped point RES[35] RES[35] -type PO PO
add mapped point RES[34] RES[34] -type PO PO
add mapped point RES[33] RES[33] -type PO PO
add mapped point RES[32] RES[32] -type PO PO
add mapped point RES[31] RES[31] -type PO PO
add mapped point RES[30] RES[30] -type PO PO
add mapped point RES[29] RES[29] -type PO PO
add mapped point RES[28] RES[28] -type PO PO
add mapped point RES[27] RES[27] -type PO PO
add mapped point RES[26] RES[26] -type PO PO
add mapped point RES[25] RES[25] -type PO PO
add mapped point RES[24] RES[24] -type PO PO
add mapped point RES[23] RES[23] -type PO PO
add mapped point RES[22] RES[22] -type PO PO
add mapped point RES[21] RES[21] -type PO PO
add mapped point RES[20] RES[20] -type PO PO
add mapped point RES[19] RES[19] -type PO PO
add mapped point RES[18] RES[18] -type PO PO
add mapped point RES[17] RES[17] -type PO PO
add mapped point RES[16] RES[16] -type PO PO
add mapped point RES[15] RES[15] -type PO PO
add mapped point RES[14] RES[14] -type PO PO
add mapped point RES[13] RES[13] -type PO PO
add mapped point RES[12] RES[12] -type PO PO
add mapped point RES[11] RES[11] -type PO PO
add mapped point RES[10] RES[10] -type PO PO
add mapped point RES[9] RES[9] -type PO PO
add mapped point RES[8] RES[8] -type PO PO
add mapped point RES[7] RES[7] -type PO PO
add mapped point RES[6] RES[6] -type PO PO
add mapped point RES[5] RES[5] -type PO PO
add mapped point RES[4] RES[4] -type PO PO
add mapped point RES[3] RES[3] -type PO PO
add mapped point RES[2] RES[2] -type PO PO
add mapped point RES[1] RES[1] -type PO PO
add mapped point RES[0] RES[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point M[3][37]/q M_reg[3][37]/Q -type DFF DFF
add mapped point M[3][34]/q M_reg[3][34]/Q -type DFF DFF
add mapped point M[3][17]/q M_reg[3][17]/Q -type DFF DFF
add mapped point M[3][28]/q M_reg[3][28]/Q -type DFF DFF
add mapped point M[3][16]/q M_reg[3][16]/Q -type DFF DFF
add mapped point M[3][15]/q M_reg[3][15]/Q -type DFF DFF
add mapped point M[3][27]/q M_reg[3][27]/Q -type DFF DFF
add mapped point M[3][14]/q M_reg[3][14]/Q -type DFF DFF
add mapped point M[3][13]/q M_reg[3][13]/Q -type DFF DFF
add mapped point M[3][33]/q M_reg[3][33]/Q -type DFF DFF
add mapped point M[3][26]/q M_reg[3][26]/Q -type DFF DFF
add mapped point M[3][12]/q M_reg[3][12]/Q -type DFF DFF
add mapped point M[3][11]/q M_reg[3][11]/Q -type DFF DFF
add mapped point M[3][25]/q M_reg[3][25]/Q -type DFF DFF
add mapped point M[3][10]/q M_reg[3][10]/Q -type DFF DFF
add mapped point M[3][9]/q M_reg[3][9]/Q -type DFF DFF
add mapped point M[3][39]/q M_reg[3][39]/Q -type DFF DFF
add mapped point M[3][38]/q M_reg[3][38]/Q -type DFF DFF
add mapped point M[3][36]/q M_reg[3][36]/Q -type DFF DFF
add mapped point M[3][32]/q M_reg[3][32]/Q -type DFF DFF
add mapped point M[3][24]/q M_reg[3][24]/Q -type DFF DFF
add mapped point M[3][8]/q M_reg[3][8]/Q -type DFF DFF
add mapped point M[3][7]/q M_reg[3][7]/Q -type DFF DFF
add mapped point M[3][23]/q M_reg[3][23]/Q -type DFF DFF
add mapped point M[3][5]/q M_reg[3][5]/Q -type DFF DFF
add mapped point M[3][31]/q M_reg[3][31]/Q -type DFF DFF
add mapped point M[3][6]/q M_reg[3][6]/Q -type DFF DFF
add mapped point M[3][22]/q M_reg[3][22]/Q -type DFF DFF
add mapped point M[3][4]/q M_reg[3][4]/Q -type DFF DFF
add mapped point M[3][3]/q M_reg[3][3]/Q -type DFF DFF
add mapped point M[3][21]/q M_reg[3][21]/Q -type DFF DFF
add mapped point M[3][2]/q M_reg[3][2]/Q -type DFF DFF
add mapped point M[3][1]/q M_reg[3][1]/Q -type DFF DFF
add mapped point M[3][35]/q M_reg[3][35]/Q -type DFF DFF
add mapped point M[3][30]/q M_reg[3][30]/Q -type DFF DFF
add mapped point M[3][20]/q M_reg[3][20]/Q -type DFF DFF
add mapped point M[3][0]/q M_reg[3][0]/Q -type DFF DFF
add mapped point M[3][19]/q M_reg[3][19]/Q -type DFF DFF
add mapped point M[3][29]/q M_reg[3][29]/Q -type DFF DFF
add mapped point M[3][18]/q M_reg[3][18]/Q -type DFF DFF
add mapped point M[2][0]/q M_reg[2][0]/Q -type DFF DFF
add mapped point M[2][1]/q M_reg[2][1]/Q -type DFF DFF
add mapped point M[2][2]/q M_reg[2][2]/Q -type DFF DFF
add mapped point M[2][3]/q M_reg[2][3]/Q -type DFF DFF
add mapped point M[2][36]/q M_reg[2][36]/Q -type DFF DFF
add mapped point M[2][4]/q M_reg[2][4]/Q -type DFF DFF
add mapped point M[2][5]/q M_reg[2][5]/Q -type DFF DFF
add mapped point M[2][6]/q M_reg[2][6]/Q -type DFF DFF
add mapped point M[2][32]/q M_reg[2][32]/Q -type DFF DFF
add mapped point M[2][7]/q M_reg[2][7]/Q -type DFF DFF
add mapped point M[2][8]/q M_reg[2][8]/Q -type DFF DFF
add mapped point M[2][9]/q M_reg[2][9]/Q -type DFF DFF
add mapped point M[2][28]/q M_reg[2][28]/Q -type DFF DFF
add mapped point M[2][10]/q M_reg[2][10]/Q -type DFF DFF
add mapped point M[2][11]/q M_reg[2][11]/Q -type DFF DFF
add mapped point M[2][12]/q M_reg[2][12]/Q -type DFF DFF
add mapped point M[2][13]/q M_reg[2][13]/Q -type DFF DFF
add mapped point M[2][14]/q M_reg[2][14]/Q -type DFF DFF
add mapped point M[2][15]/q M_reg[2][15]/Q -type DFF DFF
add mapped point M[2][16]/q M_reg[2][16]/Q -type DFF DFF
add mapped point M[2][17]/q M_reg[2][17]/Q -type DFF DFF
add mapped point M[2][18]/q M_reg[2][18]/Q -type DFF DFF
add mapped point M[2][19]/q M_reg[2][19]/Q -type DFF DFF
add mapped point M[2][20]/q M_reg[2][20]/Q -type DFF DFF
add mapped point M[2][21]/q M_reg[2][21]/Q -type DFF DFF
add mapped point M[2][22]/q M_reg[2][22]/Q -type DFF DFF
add mapped point M[2][23]/q M_reg[2][23]/Q -type DFF DFF
add mapped point M[2][24]/q M_reg[2][24]/Q -type DFF DFF
add mapped point M[2][25]/q M_reg[2][25]/Q -type DFF DFF
add mapped point M[2][26]/q M_reg[2][26]/Q -type DFF DFF
add mapped point M[2][27]/q M_reg[2][27]/Q -type DFF DFF
add mapped point M[2][29]/q M_reg[2][29]/Q -type DFF DFF
add mapped point M[2][30]/q M_reg[2][30]/Q -type DFF DFF
add mapped point M[2][31]/q M_reg[2][31]/Q -type DFF DFF
add mapped point M[2][33]/q M_reg[2][33]/Q -type DFF DFF
add mapped point M[2][34]/q M_reg[2][34]/Q -type DFF DFF
add mapped point M[2][35]/q M_reg[2][35]/Q -type DFF DFF
add mapped point M[2][37]/q M_reg[2][37]/Q -type DFF DFF
add mapped point M[2][38]/q M_reg[2][38]/Q -type DFF DFF
add mapped point M[2][39]/q M_reg[2][39]/Q -type DFF DFF
add mapped point M[1][7]/q M_reg[1][7]/Q -type DFF DFF
add mapped point M[1][8]/q M_reg[1][8]/Q -type DFF DFF
add mapped point M[1][9]/q M_reg[1][9]/Q -type DFF DFF
add mapped point M[1][10]/q M_reg[1][10]/Q -type DFF DFF
add mapped point M[1][28]/q M_reg[1][28]/Q -type DFF DFF
add mapped point M[1][11]/q M_reg[1][11]/Q -type DFF DFF
add mapped point M[1][12]/q M_reg[1][12]/Q -type DFF DFF
add mapped point M[1][13]/q M_reg[1][13]/Q -type DFF DFF
add mapped point M[1][24]/q M_reg[1][24]/Q -type DFF DFF
add mapped point M[1][14]/q M_reg[1][14]/Q -type DFF DFF
add mapped point M[1][15]/q M_reg[1][15]/Q -type DFF DFF
add mapped point M[1][16]/q M_reg[1][16]/Q -type DFF DFF
add mapped point M[1][17]/q M_reg[1][17]/Q -type DFF DFF
add mapped point M[1][18]/q M_reg[1][18]/Q -type DFF DFF
add mapped point M[1][19]/q M_reg[1][19]/Q -type DFF DFF
add mapped point M[1][20]/q M_reg[1][20]/Q -type DFF DFF
add mapped point M[1][21]/q M_reg[1][21]/Q -type DFF DFF
add mapped point M[1][22]/q M_reg[1][22]/Q -type DFF DFF
add mapped point M[1][23]/q M_reg[1][23]/Q -type DFF DFF
add mapped point M[1][25]/q M_reg[1][25]/Q -type DFF DFF
add mapped point M[1][26]/q M_reg[1][26]/Q -type DFF DFF
add mapped point M[1][27]/q M_reg[1][27]/Q -type DFF DFF
add mapped point M[1][29]/q M_reg[1][29]/Q -type DFF DFF
add mapped point M[1][30]/q M_reg[1][30]/Q -type DFF DFF
add mapped point M[1][31]/q M_reg[1][31]/Q -type DFF DFF
add mapped point M[1][32]/q M_reg[1][32]/Q -type DFF DFF
add mapped point M[1][33]/q M_reg[1][33]/Q -type DFF DFF
add mapped point M[1][34]/q M_reg[1][34]/Q -type DFF DFF
add mapped point M[1][35]/q M_reg[1][35]/Q -type DFF DFF
add mapped point M[1][38]/q M_reg[1][38]/Q -type DFF DFF
add mapped point M[1][37]/q M_reg[1][37]/Q -type DFF DFF
add mapped point M[1][39]/q M_reg[1][39]/Q -type DFF DFF
add mapped point M[1][0]/q M_reg[1][0]/Q -type DFF DFF
add mapped point M[1][1]/q M_reg[1][1]/Q -type DFF DFF
add mapped point M[1][2]/q M_reg[1][2]/Q -type DFF DFF
add mapped point M[1][3]/q M_reg[1][3]/Q -type DFF DFF
add mapped point M[1][36]/q M_reg[1][36]/Q -type DFF DFF
add mapped point M[1][4]/q M_reg[1][4]/Q -type DFF DFF
add mapped point M[1][5]/q M_reg[1][5]/Q -type DFF DFF
add mapped point M[1][6]/q M_reg[1][6]/Q -type DFF DFF
add mapped point M[0][22]/q M_reg[0][22]/Q -type DFF DFF
add mapped point M[0][23]/q M_reg[0][23]/Q -type DFF DFF
add mapped point M[0][24]/q M_reg[0][24]/Q -type DFF DFF
add mapped point M[0][25]/q M_reg[0][25]/Q -type DFF DFF
add mapped point M[0][26]/q M_reg[0][26]/Q -type DFF DFF
add mapped point M[0][27]/q M_reg[0][27]/Q -type DFF DFF
add mapped point M[0][28]/q M_reg[0][28]/Q -type DFF DFF
add mapped point M[0][29]/q M_reg[0][29]/Q -type DFF DFF
add mapped point M[0][30]/q M_reg[0][30]/Q -type DFF DFF
add mapped point M[0][31]/q M_reg[0][31]/Q -type DFF DFF
add mapped point M[0][32]/q M_reg[0][32]/Q -type DFF DFF
add mapped point M[0][33]/q M_reg[0][33]/Q -type DFF DFF
add mapped point M[0][34]/q M_reg[0][34]/Q -type DFF DFF
add mapped point M[0][35]/q M_reg[0][35]/Q -type DFF DFF
add mapped point M[0][36]/q M_reg[0][36]/Q -type DFF DFF
add mapped point M[0][37]/q M_reg[0][37]/Q -type DFF DFF
add mapped point M[0][38]/q M_reg[0][38]/Q -type DFF DFF
add mapped point M[0][39]/q M_reg[0][39]/Q -type DFF DFF
add mapped point M[0][0]/q M_reg[0][0]/Q -type DFF DFF
add mapped point M[0][7]/q M_reg[0][7]/Q -type DFF DFF
add mapped point M[0][1]/q M_reg[0][1]/Q -type DFF DFF
add mapped point M[0][5]/q M_reg[0][5]/Q -type DFF DFF
add mapped point M[0][2]/q M_reg[0][2]/Q -type DFF DFF
add mapped point M[0][3]/q M_reg[0][3]/Q -type DFF DFF
add mapped point M[0][4]/q M_reg[0][4]/Q -type DFF DFF
add mapped point M[0][6]/q M_reg[0][6]/Q -type DFF DFF
add mapped point M[0][8]/q M_reg[0][8]/Q -type DFF DFF
add mapped point M[0][9]/q M_reg[0][9]/Q -type DFF DFF
add mapped point M[0][10]/q M_reg[0][10]/Q -type DFF DFF
add mapped point M[0][17]/q M_reg[0][17]/Q -type DFF DFF
add mapped point M[0][11]/q M_reg[0][11]/Q -type DFF DFF
add mapped point M[0][12]/q M_reg[0][12]/Q -type DFF DFF
add mapped point M[0][15]/q M_reg[0][15]/Q -type DFF DFF
add mapped point M[0][13]/q M_reg[0][13]/Q -type DFF DFF
add mapped point M[0][14]/q M_reg[0][14]/Q -type DFF DFF
add mapped point M[0][16]/q M_reg[0][16]/Q -type DFF DFF
add mapped point M[0][18]/q M_reg[0][18]/Q -type DFF DFF
add mapped point M[0][19]/q M_reg[0][19]/Q -type DFF DFF
add mapped point M[0][20]/q M_reg[0][20]/Q -type DFF DFF
add mapped point M[0][21]/q M_reg[0][21]/Q -type DFF DFF
add mapped point rB[23]/q rB_reg[23]/Q -type DFF DFF
add mapped point rA[6]/q rA_reg[6]/Q -type DFF DFF
add mapped point rB[9]/q rB_reg[9]/Q -type DFF DFF
add mapped point rA[4]/q rA_reg[4]/Q -type DFF DFF
add mapped point rA[7]/q rA_reg[7]/Q -type DFF DFF
add mapped point rB[1]/q rB_reg[1]/Q -type DFF DFF
add mapped point rA[11]/q rA_reg[11]/Q -type DFF DFF
add mapped point rB[0]/q rB_reg[0]/Q -type DFF DFF
add mapped point rA[13]/q rA_reg[13]/Q -type DFF DFF
add mapped point rA[5]/q rA_reg[5]/Q -type DFF DFF
add mapped point rB[4]/q rB_reg[4]/Q -type DFF DFF
add mapped point rB[20]/q rB_reg[20]/Q -type DFF DFF
add mapped point rA[15]/q rA_reg[15]/Q -type DFF DFF
add mapped point rA[3]/q rA_reg[3]/Q -type DFF DFF
add mapped point rB[19]/q rB_reg[19]/Q -type DFF DFF
add mapped point rA[0]/q rA_reg[0]/Q -type DFF DFF
add mapped point rB[21]/q rB_reg[21]/Q -type DFF DFF
add mapped point rB[6]/q rB_reg[6]/Q -type DFF DFF
add mapped point rB[17]/q rB_reg[17]/Q -type DFF DFF
add mapped point rB[16]/q rB_reg[16]/Q -type DFF DFF
add mapped point rB[15]/q rB_reg[15]/Q -type DFF DFF
add mapped point rB[3]/q rB_reg[3]/Q -type DFF DFF
add mapped point rA[12]/q rA_reg[12]/Q -type DFF DFF
add mapped point rA[10]/q rA_reg[10]/Q -type DFF DFF
add mapped point rB[8]/q rB_reg[8]/Q -type DFF DFF
add mapped point rB[11]/q rB_reg[11]/Q -type DFF DFF
add mapped point rA[2]/q rA_reg[2]/Q -type DFF DFF
add mapped point rB[2]/q rB_reg[2]/Q -type DFF DFF
add mapped point rA[9]/q rA_reg[9]/Q -type DFF DFF
add mapped point rB[12]/q rB_reg[12]/Q -type DFF DFF
add mapped point rB[13]/q rB_reg[13]/Q -type DFF DFF
add mapped point rB[7]/q rB_reg[7]/Q -type DFF DFF
add mapped point rA[1]/q rA_reg[1]/Q -type DFF DFF
add mapped point rA[8]/q rA_reg[8]/Q -type DFF DFF
add mapped point rB[10]/q rB_reg[10]/Q -type DFF DFF
add mapped point rA[14]/q rA_reg[14]/Q -type DFF DFF
add mapped point rB[22]/q rB_reg[22]/Q -type DFF DFF
add mapped point rB[14]/q rB_reg[14]/Q -type DFF DFF
add mapped point rB[5]/q rB_reg[5]/Q -type DFF DFF
add mapped point rB[18]/q rB_reg[18]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
